### PR TITLE
Version 2.7.0

### PR DESCRIPTION
**Pull request by glennmorris**

### CODE REVIEW

**Review by jhoblitt — CHANGES_REQUESTED** [review]
The version/release PRs shouldn't appear in the changelog.  The `skip-changelog` label should be added to https://github.com/lsst-it/puppet-ccs_software/pull/68 and the changelog regenerated.

**Comment by jhoblitt** [comment]
The same for this PR, the `skip-changelog` labeled should be added.

**Comment by glennmorris** [comment]
> The same for this PR, the `skip-changelog` label should be added.

I never knew what the purpose of skip-changelog was.
I have added the label, but have no idea how to correct the changelog, except edit it by hand.
(How can my local repo where I generate the changelog know about github pull request labels?)

**Comment by jhoblitt** [comment]
> (How can my local repo where I generate the changelog know about github pull request labels?)

GCG, called by rake, uses the github api.  `bundle exec rake release:porcelain:changelog` will regenerate only the changelog.

**Comment by glennmorris** [comment]
> > (How can my local repo where I generate the changelog know about github pull request labels?)
> 
> GCG, called by rake, uses the github api. `bundle exec rake release:porcelain:changelog` will regenerate only the changelog.

Got it, thanks.
I have re-regenerated the changelog...

**Review by jhoblitt — APPROVED** [review]

**Pull request merged**
