### PR TITLE
normalize supported operating systems

### PR DESCRIPTION
**Pull request by jhoblitt**

### CODE REVIEW

**Comment by jhoblitt** [comment]
This should pass after being rebased on #27

**Review by glennmorris — APPROVED** [review]

**Comment by jhoblitt** [comment]
It looks like the puppet/alternatives mod, which is only used to setup the acceptance tests, might be broke on EL9.

**Comment by jhoblitt** [comment]
Ugh, so the acceptance tests aren't going to pass on EL9 for this module because of the jdk8 rpms.

**Comment by jhoblitt** [comment]
I'm removing EL9 from the support OS list.

**Pull request merged**
